package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MovieAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovieAllPropertiesEquals(Movie expected, Movie actual) {
        assertMovieAutoGeneratedPropertiesEquals(expected, actual);
        assertMovieAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovieAllUpdatablePropertiesEquals(Movie expected, Movie actual) {
        assertMovieUpdatableFieldsEquals(expected, actual);
        assertMovieUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovieAutoGeneratedPropertiesEquals(Movie expected, Movie actual) {
        assertThat(actual)
            .as("Verify Movie auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovieUpdatableFieldsEquals(Movie expected, Movie actual) {
        assertThat(actual)
            .as("Verify Movie relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getPlot()).as("check plot").isEqualTo(expected.getPlot()))
            .satisfies(a -> assertThat(a.getFullplot()).as("check fullplot").isEqualTo(expected.getFullplot()))
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()))
            .satisfies(a -> assertThat(a.getRuntime()).as("check runtime").isEqualTo(expected.getRuntime()))
            .satisfies(a -> assertThat(a.getRated()).as("check rated").isEqualTo(expected.getRated()))
            .satisfies(a -> assertThat(a.getReleased()).as("check released").isEqualTo(expected.getReleased()))
            .satisfies(a -> assertThat(a.getGenres()).as("check genres").isEqualTo(expected.getGenres()))
            .satisfies(a -> assertThat(a.getCast()).as("check cast").isEqualTo(expected.getCast()))
            .satisfies(a -> assertThat(a.getLanguages()).as("check languages").isEqualTo(expected.getLanguages()))
            .satisfies(a -> assertThat(a.getPoster()).as("check poster").isEqualTo(expected.getPoster()))
            .satisfies(a -> assertThat(a.getImdbRating()).as("check imdbRating").isEqualTo(expected.getImdbRating()))
            .satisfies(a -> assertThat(a.getImdbVotes()).as("check imdbVotes").isEqualTo(expected.getImdbVotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovieUpdatableRelationshipsEquals(Movie expected, Movie actual) {
        // empty method
    }
}
